on:
  push:
    branches:
      - main

jobs:
  test:
    name: test_github_var
    runs-on: ubuntu-latest
    steps:
      - name: test_github_var
        uses: appleboy/scp-action@master
        with:
          source: '.'
          target: '/root'
          username: root
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PSWD }}