on:
  push:
    branches:
      - main

jobs:
  test:
    name: test_github_var
    runs-on: ubuntu-latest
    steps:
      - name: test_github_var
        run: |
          sudo apt install -y sshpass
          sshpass -p ${{secrets.PSWD}} ssh root@${{secrets.HOST}}